FROM node:18

# Set the working directory in the container
WORKDIR /workspaces/bundle-start

# Make the script executable
# RUN chmod +x .devcontainer/install_dependencies.sh

ENV LANG="C.UTF-8"

# Install beyond
RUN npm i -g beyond@1.2.4
